[build]
  command = "npm run build"
  publish = "dist/budget-tracker-frontend/browser"

[[redirects]]
  from = "/documentation/*"
  to = "/documentation/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
