export enum Category {
  /* Incomes */
  SALARY = 'SALARY',
  POCKET_MONEY = 'POCKET_MONEY',
  ALIMENT = 'ALIMENT',
  CAPITAL_ASSETS = 'CAPITAL_ASSETS',
  RENTAL = 'RENTAL',

  /* Expenses */
  GROCERIES = 'GROCERIES',
  DRUGSTORE = 'DRUGSTORE',
  FREE_TIME = 'FREE_TIME',
  RENT = 'RENT',
  INSURANCE = 'INSURANCE',
  SUBSCRIPTIONS = 'SUBSCRIPTIONS',
  EDUCATION = 'EDUCATION',

  OTHER = 'OTHER'
}
